version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_lab
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "123456"
      MARIADB_DATABASE: "laboratorios"
      MARIADB_USER: "labuser"
      MARIADB_PASSWORD: "lab123"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    container_name: adminer_lab
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
